services:
  - type: web
    name: vecino-backend
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        value: tu_url_db
      - key: JWT_SECRET
        value: tu_secreto
      # ... otras variables backend

  - type: web
    name: vecino-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: VITE_API_URL
        value: https://vecino-backend-xxxxxx.onrender.com/api



